# Publish to PowerShell Gallery with this key
environment:
  NuGetApiKey:
    secure: VMvVbhuMaUTbI8WgnJH/WF7UBGwj261AgERGm25s21zQErHoIdwacoF3yd6OjIWh

os: WMF 5

# Skip on updates to the readme.
skip_commits:
  message: /updated readme.*|update readme.*s/

build: false

test_script:
- ps: . .\build.ps1

on_finish:
- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
